# Generated by Django 2.1.1 on 2018-09-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=100, verbose_name='Contact Number')),
                ('current_address', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('associated_names', models.TextField()),
                ('previous_addresses', models.TextField()),
                ('possible_relatives', models.TextField()),
                ('possible_associates', models.TextField()),
                ('possible_businesses', models.TextField()),
                ('cases', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('patron_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=100, verbose_name='Contact Number')),
                ('current_address', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('associated_names', models.TextField()),
                ('previous_addresses', models.TextField()),
                ('possible_relatives', models.TextField()),
                ('possible_associates', models.TextField()),
                ('possible_businesses', models.TextField()),
                ('cases', models.TextField()),
                ('links', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='associates',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spyderapp.Patron'),
        ),
    ]
